<a href="https://colab.research.google.com/github/Ruthikajayaprakash/Rain-prediction-using-machinelearning/blob/main/machine_learning_RAIN_forecast_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib .pyplot as plt
from google.colab import files
import io
import pandas as pd

data = files.upload()

Saving weatherAUS.csv to weatherAUS.csv


IMPORTING DATASET


In [4]:
dataset = pd.read_csv("weatherAUS.csv")
x = dataset.iloc[:,[1,2,3,4,5,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
y = dataset.iloc[:,-1].values

In [5]:
print(x)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


In [6]:
print(y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [7]:
y = y.reshape(-1,1) ##used to change 1d list to 2d list

In [8]:
print(y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


Dealing invalid dataset

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
x = imputer.fit_transform(x)
y = imputer.fit_transform(y)


In [10]:
print(x)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 20.0 ... 15.0 20.9 'No']]


In [11]:
print(y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


encoding **dataset**

In [12]:
from sklearn .preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,0] = le1.fit_transform(x[:,0])
le2 = LabelEncoder()
x[:,4] = le2.fit_transform(x[:,4])
le3 = LabelEncoder()
x[:,6] = le3.fit_transform(x[:,6])
le4 = LabelEncoder()
x[:,7] = le4.fit_transform(x[:,7])
le5 = LabelEncoder()
x[:,-1] = le4.fit_transform(x[:,-1])
le6 = LabelEncoder()
y = le6.fit_transform(y)




/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
print(x)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]


In [14]:
print(y)

[0 0 0 ... 0 0 0]


*FEATRURE SCALING

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [16]:
print(x)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


splitting dataset into training set and test set


In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)


In [18]:
print(x_train)

[[ 0.22535368  1.03946939  0.07140543 ...  0.68369032  0.08145488
  -0.52979545]
 [ 1.42012717 -0.45263203  0.11369237 ... -0.41722163  0.22733303
  -0.52979545]
 [ 0.50647685 -0.20133073 -0.14002932 ... -0.06058818 -0.02065982
   1.88752093]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]


In [20]:
print(y_train)

[1 0 0 ... 0 0 0]


Training model

In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [22]:
classifier.score(x_train,y_train)

0.999905472294789

In [23]:
y_pred =  classifier.predict(x_test)

In [24]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [25]:
y_pred = le6.inverse_transform(y_pred)

In [26]:
print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [27]:
print(y_test)

[1 1 0 ... 1 0 0]


In [28]:
y_test = le6.inverse_transform(y_test)

In [29]:
print(y_test)

['Yes' 'Yes' 'No' ... 'Yes' 'No' 'No']


In [30]:
y_test = y_test.reshape(-1,1)
y_pred = y_pred.reshape(-1,1)

In [31]:
df = np.concatenate((y_test,y_pred),axis = 1)
dataframe = pd.DataFrame(df,columns=['Rain on Tomorrow','Prediction of  Rain'])

In [33]:
print(df)

[['Yes' 'No']
 ['Yes' 'No']
 ['No' 'No']
 ...
 ['Yes' 'No']
 ['No' 'No']
 ['No' 'No']]


In [32]:
print(dataframe)

      Rain on Tomorrow Prediction of  Rain
0                  Yes                  No
1                  Yes                  No
2                   No                  No
3                   No                 Yes
4                   No                  No
...                ...                 ...
29087               No                 Yes
29088               No                  No
29089              Yes                  No
29090               No                  No
29091               No                  No

[29092 rows x 2 columns]


In [34]:
dataframe.to_csv('prediction.csv')

calculating accuracy


In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8540492231541317

In [36]:
dataframe.to_csv('prediction.csv')